name: Build APK
on:
  push:
    branches: [ "develop" ]

jobs:
  Build-and-Push:
    runs-on: "ubuntu-latest"
    if: "contains(github.event.head_commit.message, 'build')"
    
    steps:
    
      - name: "Checkout Code"
        uses: actions/checkout@v3

      - name: "Build and Release"
        run: |
          chmod a+x gradlew
          ./gradlew build
          ./gradlew assembleRelease
          ./gradlew app:bundleRelease
        env:
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.STORE_PASSWORD }}

      - name: "upload artefact to App Center"
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: "srinivasan-vthink.co.in/test"
          token: ${{secrets.APP_CENTER_TOKEN}}
          file: ./app/build/outputs/apk/release/app-release.apk
          group: "tester" 
          notifyTesters: "true"